Restaurante "AsturDonal" fecha 01-02-2015
Ingredientes{ 
	Ingrediente:CODI1 'moluscos' infoURL "https://es.wikipedia.org/wiki/Mollusca" alergico
	Ingrediente: CODI2 'altramuz' infoURL "https://es.wikipedia.org/wiki/Anagyris_foetida" alergico
	Ingrediente: CODI3 'lechuga' infoURL "https://es.wikipedia.org/wiki/Lactuca_sativa" 
	Ingrediente: CODI4 'pollo' infoURL "https://es.wikipedia.org/wiki/Pollo" foto "pollo.jpg"
	Ingrediente: CODI5 'queso' infoURL "https://es.wikipedia.org/wiki/Queso" foto "queso.jpg"
	Ingrediente: CODI6 'cereales' infoURL "https://es.wikipedia.org/wiki/Cereal" alergico
	Ingrediente: CODI7 'crustaceos' alergico
	Ingrediente: CODI8 'huevos'  foto "huevos.jpg" alergico
	Ingrediente: CODI9 'pescado' foto "pescado.jpg"
	Ingrediente: CODI10 'cacahuetes' alergico
	Ingrediente: CODI11 'pan' infoURL "https://es.wikipedia.org/wiki/Pan"
	Ingrediente: CODI12 'soja' infoURL "https://es.wikipedia.org/wiki/Soja" alergico
	Ingrediente: CODI13 'leche' infoURL "https://es.wikipedia.org/wiki/Leche" foto "leche.jpg" alergico
	Ingrediente: CODI14 'frutos secos' alergico
	Ingrediente: CODI15 'apio' infoURL "https://es.wikipedia.org/wiki/Apio" alergico
	Ingrediente: CODI16 'mostaza' infoURL "https://es.wikipedia.org/wiki/Mostaza" alergico
	Ingrediente: CODI17 'semillas de sesamo' alergico
	Ingrediente: CODI18 'dioxito de azufre y sulfitos' alergico
	Ingrediente: CODI19 'croutons' infoURL "https://es.wikipedia.org/wiki/Crouton"
	Ingrediente: CODI20 'tomate' infoURL "https://es.wikipedia.org/wiki/Tomate" 
	Ingrediente: CODI21 'pepinillo' infoURL "https://es.wikipedia.org/wiki/Pepino" 
	Ingrediente: CODI22 'chocolate' infoURL "https://es.wikipedia.org/wiki/Chocolate" 
	
}

